---
kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat-config
  annotations:
    kubesphere.io/creator: admin
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      # 忽略在指定的时间跨度之前修改的所有文件
      ignore_older: 24h
      # 关闭文件句柄时间
      close_inactive: 60m
      encoding: plain
      exclude_files: ['\.gz$']
      paths:
        - /data/logs/auth/*/auth_dot.json
      fields:
        log_topics: auth_topic_data_dot
      tags: ["cheese-auth-service"]
    processors:
      - drop_fields:
          fields: ["input.type", "prospector.type", "prospector.type"]
    output.kafka:
      hosts: ["kafka-kafka-brokers.kafka.svc.cluster.local:9092"]
      topic: '%{[fields][log_topics]}'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: none
      max_message_bytes: 1000000

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirst
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.2
        args: [
          "-c", "/etc/filebeat.yml",
          "-path.logs", "/var/share/filebeat/logs",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /data/logs
          name: cheese-log
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/share/filebeat/logs
      
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: cheese-log
        hostPath:
           path: /data/logs
      - name: data
        hostPath:
            # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
            path: /data/filebeat-data
      - name: varlog
        hostPath:
          path: /data/filebeat-log

