apiVersion: v1
kind: Service
metadata:
  name: rabbit-ui 
  
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 15672-15672-tcp
    nodePort: 31672
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app.kubernetes.io/name: warm-rabbit-cluster
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

