apiVersion: v1
kind: Service
metadata: 
   name: consul-ui
   labels:
     name: consul-ui
spec:
   type: NodePort
   ports:
    - name: 8500-8500-tcp
      nodePort: 30580
      port: 8500
      protocol: TCP
      targetPort: 8500
   selector:
    app: consul
