
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          image: 'zenko/kafka-manager:1.3.3.22'
          ports:
            - name: kafka-manager
              containerPort: 9000
              protocol: TCP
          env:
            - name: ZK_HOSTS
              value: 'zoo-entrance:2181'
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


--- 
# 暴漏服务
kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    app: kafka-manager
spec:
  ports:
    - name: kafka
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
  selector:
    app: kafka-manager
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
