kind: Deployment
apiVersion: apps/v1
metadata:
  name: zoo-entrance
  namespace: kafka
  labels:
    app: zoo-entrance
 spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo-entrance
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zoo-entrance
    spec:
      volumes:
        - name: cluster-operator-certs
          secret:
            secretName: kafka-cluster-operator-certs
            defaultMode: 288
        - name: cluster-ca-certs
          secret:
            secretName: kafka-cluster-ca-cert
            defaultMode: 288
      containers:
        - name: zoo-entrance
          image: 'ghcr.io/scholzj/zoo-entrance:latest'
          command:
            - /opt/stunnel/stunnel_run.sh
          ports:
            - name: zoo
              containerPort: 2181
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: notice
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: 'kafka-zookeeper-client:2181'
          resources: {}
          volumeMounts:
            - name: cluster-operator-certs
              mountPath: /etc/cluster-operator-certs/
            - name: cluster-ca-certs
              mountPath: /etc/cluster-ca-certs/
          livenessProbe:
            exec:
              command:
                - /opt/stunnel/stunnel_healthcheck.sh
                - '2181'
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /opt/stunnel/stunnel_healthcheck.sh
                - '2181'
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: zoo-entrance
  namespace: kafka
  labels:
    app: zoo-entrance
spec:
  ports:
    - name: zoo
      protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    app: zoo-entrance
  type: ClusterIP
  sessionAffinity: None

